import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import CodeMirror from '@uiw/react-codemirror'
import { sql as sqlLanguage } from '@codemirror/lang-sql'
import { oneDark } from '@codemirror/theme-one-dark'
import { Activity, AlertCircle, Check, ChevronDown, ChevronRight, CircleDot, Database, FilePlus2, FolderOpen, Lock, Moon, Play, Plus, RefreshCw, Save, Search, Settings2, Square, Sun, Table2, Trash2, X, Zap } from 'lucide-react'
import type { Connection, PendingChange, QueryResult, Structure, TableInfo } from '../shared/types'
import './styles.css'

type Tab = { id: string; kind: 'table' | 'structure' | 'query'; title: string; table?: string; sql?: string }
type Toast = { type: 'success' | 'error' | 'info'; text: string }

const uid = () => crypto.randomUUID()
const formatValue = (value: unknown) => value === null ? 'NULL' : typeof value === 'object' ? JSON.stringify(value) : String(value)

function App() {
  const [connections, setConnections] = useState<Connection[]>([])
  const [connected, setConnected] = useState<string[]>([])
  const [schema, setSchema] = useState<Record<string, TableInfo[]>>({})
  const [expanded, setExpanded] = useState<Record<string, boolean>>({})
  const [tabs, setTabs] = useState<Tab[]>([])
  const [activeTab, setActiveTab] = useState<string | null>(null)
  const [sqlText, setSqlText] = useState('SELECT name, type FROM sqlite_master WHERE type IN (\'table\', \'view\') ORDER BY type, name;')
  const [results, setResults] = useState<Record<string, QueryResult>>({})
  const [structures, setStructures] = useState<Record<string, Structure>>({})
  const [pending, setPending] = useState<Record<string, PendingChange[]>>({})
  const [loading, setLoading] = useState(false)
  const [theme, setTheme] = useState<'dark' | 'light'>('dark')
  const [toast, setToast] = useState<Toast | null>(null)
  const [filter, setFilter] = useState('')
  const [page, setPage] = useState(0)
  const [sort, setSort] = useState<{ column?: string; direction?: 'asc' | 'desc' }>({})

  useEffect(() => { window.sqlConnect.settings.load().then(setConnections); const saved = localStorage.getItem('sql-connect-theme') as 'dark' | 'light' | null; if (saved) setTheme(saved) }, [])
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('sql-connect-theme', theme) }, [theme])
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(null), 3800); return () => clearTimeout(timer) } }, [toast])
  const active = tabs.find(t => t.id === activeTab)
  const activeConnection = active?.id.split(':')[0] || connected[0] || ''

  const persist = (next: Connection[]) => { setConnections(next); void window.sqlConnect.settings.save(next) }
  const notify = (text: string, type: Toast['type'] = 'info') => setToast({ text, type })

  async function addConnection(create = false) {
    const path = create ? await window.sqlConnect.dialog.saveFile() : await window.sqlConnect.dialog.openFile()
    if (!path) return
    const name = path.split('/').pop()?.replace(/\.(sqlite|sqlite3|db)$/i, '') || 'SQLite 数据库'
    const item: Connection = { id: uid(), name, path, readonly: false, create }
    await connect(item)
  }
  async function connect(item: Connection) { setLoading(true); try { await window.sqlConnect.db.connect(item); setConnected(v => [...new Set([...v, item.id])]); const items = await window.sqlConnect.db.schema(item.id); setSchema(v => ({ ...v, [item.id]: items })); setExpanded(v => ({ ...v, [item.id]: true })); const saved = { ...item }; delete saved.create; setConnections(v => v.some(c => c.id === saved.id) ? v.map(c => c.id === saved.id ? saved : c) : [...v, saved]); void window.sqlConnect.settings.save(connections.some(c => c.id === saved.id) ? connections.map(c => c.id === saved.id ? saved : c) : [...connections, saved]); notify(`已连接 ${item.name}`, 'success') } catch (error) { notify(error instanceof Error ? error.message : String(error), 'error') } finally { setLoading(false) } }
  async function disconnect(id: string) { await window.sqlConnect.db.disconnect(id); setConnected(v => v.filter(item => item !== id)); setSchema(v => { const copy = { ...v }; delete copy[id]; return copy }); setTabs(v => v.filter(t => !t.id.startsWith(`${id}:`))); notify('连接已断开') }
  async function openTable(connectionId: string, item: TableInfo, kind: Tab['kind'] = 'table') {
    const id = `${connectionId}:${kind}:${item.name}`; setTabs(v => v.some(t => t.id === id) ? v : [...v, { id, kind, title: item.name, table: item.name }]); setActiveTab(id); setPage(0); setFilter('')
    if (kind === 'structure') { if (!structures[id]) setStructures(v => ({ ...v, [id]: undefined as never })); try { const structure = await window.sqlConnect.db.structure(connectionId, item.name); setStructures(v => ({ ...v, [id]: structure })) } catch (error) { notify(error instanceof Error ? error.message : String(error), 'error') } }
    else await refreshTable(connectionId, item.name, id)
  }
  async function refreshTable(connectionId: string, table: string, tabId = activeTab || '') { setLoading(true); try { const data = await window.sqlConnect.db.query(connectionId, table, { offset: page * 100, limit: 100, orderBy: sort.column, direction: sort.direction, filter }); setResults(v => ({ ...v, [tabId]: data })) } catch (error) { notify(error instanceof Error ? error.message : String(error), 'error') } finally { setLoading(false) } }
  async function runSql(sqlOverride?: string) { const text = (sqlOverride ?? sqlText).trim(); if (!text || !activeConnection) return; const id = `${activeConnection}:query:${uid()}`; const title = text.split(/\s+/).slice(0, 4).join(' '); setTabs(v => [...v, { id, kind: 'query', title, sql: text }]); setActiveTab(id); setLoading(true); try { const data = await window.sqlConnect.db.execute(activeConnection, text); setResults(v => ({ ...v, [id]: data })); notify(data.changes !== undefined ? `执行成功，影响 ${data.changes} 行` : `查询完成，用时 ${data.elapsedMs} ms`, 'success') } catch (error) { notify(error instanceof Error ? error.message : String(error), 'error') } finally { setLoading(false) } }
  function updateCell(tabId: string, row: Record<string, unknown>, column: string, value: string) { const tab = tabs.find(t => t.id === tabId); if (!tab?.table) return; const key = String(row.__sqlconnect_rowid ?? JSON.stringify(row)); setResults(v => ({ ...v, [tabId]: { ...v[tabId], rows: v[tabId].rows.map(r => String(r.__sqlconnect_rowid ?? JSON.stringify(r)) === key ? { ...r, [column]: value } : r) } })); setPending(v => ({ ...v, [tabId]: [...(v[tabId] || []).filter(c => !(c.type === 'update' && String(c.rowid) === String(row.__sqlconnect_rowid))), { type: 'update', table: tab.table!, rowid: row.__sqlconnect_rowid as string | number, values: { [column]: value }, original: { [column]: row[column] } }] })) }
  function addRow(tabId: string) { const tab = tabs.find(t => t.id === tabId); const result = results[tabId]; if (!tab?.table || !result) return; const row = Object.fromEntries(result.columns.filter(c => c !== '__sqlconnect_rowid').map(c => [c, null])); setResults(v => ({ ...v, [tabId]: { ...v[tabId], rows: [...v[tabId].rows, row] } })); setPending(v => ({ ...v, [tabId]: [...(v[tabId] || []), { type: 'insert', table: tab.table!, values: row }] })) }
  function deleteRow(tabId: string, row: Record<string, unknown>) { const tab = tabs.find(t => t.id === tabId); if (!tab?.table) return; setResults(v => ({ ...v, [tabId]: { ...v[tabId], rows: v[tabId].rows.filter(r => r !== row) } })); setPending(v => ({ ...v, [tabId]: [...(v[tabId] || []), { type: 'delete', table: tab.table!, rowid: row.__sqlconnect_rowid as string | number, values: {}, original: row }] })) }
  async function commit(tabId: string) { const changes = pending[tabId] || []; if (!changes.length) return; const connectionId = tabId.split(':')[0]; setLoading(true); try { await window.sqlConnect.db.apply(connectionId, changes); setPending(v => ({ ...v, [tabId]: [] })); notify(`已提交 ${changes.length} 项修改`, 'success'); const tab = tabs.find(t => t.id === tabId); if (tab?.table) await refreshTable(connectionId, tab.table, tabId) } catch (error) { notify(error instanceof Error ? error.message : String(error), 'error') } finally { setLoading(false) } }
  function discard(tabId: string) { setPending(v => ({ ...v, [tabId]: [] })); const tab = tabs.find(t => t.id === tabId); if (tab?.table) void refreshTable(tabId.split(':')[0], tab.table, tabId) }
  const result = activeTab ? results[activeTab] : undefined
  const activeChanges = activeTab ? pending[activeTab] || [] : []
  const newQuery = () => { const connectionId = connected[0]; if (!connectionId) { notify('请先连接一个 SQLite 数据库', 'info'); return } const id = `${connectionId}:query:${uid()}`; setTabs(v => [...v, { id, kind: 'query', title: 'SQL 查询', sql: '' }]); setActiveTab(id); setSqlText('') }

  return <div className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Database size={18}/></div><span>SQL Connect</span><span className="version">SQLite</span></div><div className="top-actions"><button className="icon-btn" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} title="切换主题">{theme === 'dark' ? <Sun size={17}/> : <Moon size={17}/>}</button><button className="icon-btn" title="设置"><Settings2 size={17}/></button></div></header>
    <div className="main-layout">
      <aside className="sidebar">
        <div className="sidebar-head"><div><div className="eyebrow">WORKSPACE</div><h2>连接</h2></div><button className="icon-btn accent" onClick={() => void addConnection()} title="打开 SQLite"><Plus size={18}/></button></div>
        <div className="quick-actions"><button onClick={() => void addConnection()}><FolderOpen size={15}/>打开文件</button><button onClick={() => void addConnection(true)}><FilePlus2 size={15}/>新建数据库</button></div>
        <div className="connection-list">{connections.length === 0 && <div className="empty-connect"><Database size={28}/><p>还没有连接</p><span>打开一个 SQLite 文件开始</span></div>}{connections.map(item => <div className="connection-block" key={item.id}><button className="tree-row connection-row" onClick={() => connected.includes(item.id) ? setExpanded(v => ({ ...v, [item.id]: !v[item.id] })) : void connect(item)}><span className="chevron">{expanded[item.id] ? <ChevronDown size={15}/> : <ChevronRight size={15}/>}</span><CircleDot size={13} className={connected.includes(item.id) ? 'connected-dot' : 'offline-dot'}/><span className="tree-label">{item.name}</span>{connected.includes(item.id) && <span className="connected-label">在线</span>}<span className="readonly-control" title={item.readonly ? '只读连接' : '读写连接'} onClick={event => { event.stopPropagation(); const next = { ...item, readonly: !item.readonly }; persist(connections.map(c => c.id === item.id ? next : c)); if (connected.includes(item.id)) void disconnect(item.id).then(() => connect(next)) }}>{item.readonly ? <Lock size={12}/> : <span>RW</span>}</span></button>{expanded[item.id] && connected.includes(item.id) && <div className="tree-children"><div className="tree-section-label">表和视图</div>{(schema[item.id] || []).map(table => <div className="object-row" key={table.name}><button onClick={() => void openTable(item.id, table)}><Table2 size={14}/><span>{table.name}</span><span className="object-type">{table.type === 'view' ? 'VIEW' : 'TABLE'}</span></button><button className="structure-btn" onClick={() => void openTable(item.id, table, 'structure')} title="查看结构"><Settings2 size={13}/></button></div>)}{!(schema[item.id] || []).length && <div className="tree-hint">暂无表或视图</div>}</div>}</div>)}</div>
        {connections.length > 0 && <div className="sidebar-footer"><button onClick={() => { const item = connections.find(c => connected.includes(c.id)); if (item) void disconnect(item.id) }}><X size={14}/>断开当前连接</button></div>}
      </aside>
      <main className="workspace">
        <div className="tabbar">{tabs.length === 0 && <div className="tabbar-placeholder">选择一个表，或打开 SQL 查询</div>}{tabs.map(tab => <button className={`tab ${tab.id === activeTab ? 'active' : ''}`} key={tab.id} onClick={() => { setActiveTab(tab.id); if (tab.kind === 'query') setSqlText(tab.sql || '') }}><span className="tab-dot">{tab.kind === 'query' ? <Zap size={12}/> : tab.kind === 'structure' ? <Settings2 size={12}/> : <Table2 size={12}/>}</span><span>{tab.title}</span><X size={13} onClick={(event) => { event.stopPropagation(); if ((pending[tab.id] || []).length && !confirm('当前页面有未提交修改，确定关闭吗？')) return; setTabs(v => v.filter(t => t.id !== tab.id)); if (activeTab === tab.id) setActiveTab(tabs.find(t => t.id !== tab.id)?.id || null) }}/></button>)}<button className="new-query" onClick={newQuery}><Plus size={15}/>SQL</button></div>
        <div className="content-area">{!active && <Welcome onOpen={() => void addConnection()} onCreate={() => void addConnection(true)} onQuery={newQuery} />}{active?.kind === 'structure' && <StructureView structure={structures[active.id]} />}{active?.kind === 'table' && result && <DataView tab={active} result={result} readonly={connections.find(c => c.id === activeConnection)?.readonly} filter={filter} setFilter={setFilter} page={page} setPage={setPage} sort={sort} setSort={setSort} onRefresh={() => active.table && void refreshTable(activeConnection, active.table)} onEdit={updateCell} onAdd={() => addRow(active.id)} onDelete={deleteRow} changes={activeChanges} onCommit={() => void commit(active.id)} onDiscard={() => discard(active.id)} />}{active?.kind === 'query' && <QueryView sql={sqlText} setSql={setSqlText} onRun={() => void runSql(sqlText)} loading={loading} result={result} />}</div>
        <footer className="statusbar"><span><span className={`status-dot ${loading ? 'busy' : ''}`}></span>{loading ? '正在执行…' : activeConnection ? '已就绪' : '未连接数据库'}</span>{activeConnection && <span className="status-path">{connections.find(c => c.id === activeConnection)?.path}</span>}<span className="status-spacer"/><span>UTF-8</span><span>SQL Connect 0.1</span></footer>
      </main>
    </div>
    {toast && <div className={`toast ${toast.type}`}><span>{toast.type === 'success' ? <Check size={16}/> : toast.type === 'error' ? <AlertCircle size={16}/> : <Activity size={16}/>}</span>{toast.text}</div>}
  </div>
}

function Welcome({ onOpen, onCreate, onQuery }: { onOpen: () => void; onCreate: () => void; onQuery: () => void }) { return <div className="welcome"><div className="welcome-icon"><Database size={32}/></div><h1>开始连接 SQLite</h1><p>打开一个本地数据库文件，浏览表结构、编辑数据或运行 SQL。</p><div className="welcome-actions"><button className="primary-btn" onClick={onOpen}><FolderOpen size={17}/>打开 SQLite 文件</button><button className="secondary-btn" onClick={onCreate}><FilePlus2 size={17}/>创建新数据库</button></div><button className="welcome-query" onClick={onQuery}><Zap size={14}/>连接后打开 SQL 查询</button><div className="feature-row"><span><Table2 size={15}/>表结构浏览</span><span><Zap size={15}/>SQL 查询</span><span><Save size={15}/>安全提交修改</span></div></div> }

function DataView({ tab, result, readonly, filter, setFilter, page, setPage, sort, setSort, onRefresh, onEdit, onAdd, onDelete, changes, onCommit, onDiscard }: any) { const columns = result.columns.filter((c: string) => c !== '__sqlconnect_rowid'); return <div className="panel"><div className="panel-head"><div><div className="eyebrow">DATA TABLE</div><h1>{tab.table}</h1></div><div className="panel-actions"><div className="search-box"><Search size={15}/><input value={filter} onChange={e => setFilter(e.target.value)} onKeyDown={e => e.key === 'Enter' && onRefresh()} placeholder="筛选当前表…"/></div><button className="toolbar-btn" onClick={onRefresh}><RefreshCw size={15}/>刷新</button>{changes.length > 0 && !readonly && <><button className="toolbar-btn danger" onClick={onDiscard}><X size={15}/>放弃</button><button className="toolbar-btn primary" onClick={onCommit}><Save size={15}/>提交 {changes.length}</button></>}</div></div><div className="table-wrap"><table><thead><tr><th className="row-number">#</th>{columns.map((column: string) => <th key={column} onClick={() => setSort({ column, direction: sort.column === column && sort.direction === 'asc' ? 'desc' : 'asc' })}>{column}<span className="sort-indicator">{sort.column === column ? sort.direction === 'asc' ? '↑' : '↓' : '↕'}</span></th>)}<th></th></tr></thead><tbody>{result.rows.map((row: Record<string, unknown>, index: number) => <tr key={String(row.__sqlconnect_rowid ?? index)}><td className="row-number">{page * 100 + index + 1}</td>{columns.map((column: string) => <td key={column}><input disabled={readonly} className={changes.some((c: PendingChange) => c.type === 'update' && c.rowid === row.__sqlconnect_rowid && c.values[column] !== undefined) ? 'dirty-cell' : ''} value={row[column] === null ? '' : String(row[column] ?? '')} placeholder={row[column] === null ? 'NULL' : ''} onChange={e => onEdit(tab.id, row, column, e.target.value)}/></td>)}<td>{!readonly && <button className="row-delete" onClick={() => onDelete(tab.id, row)}><Trash2 size={14}/></button>}</td></tr>)}{!result.rows.length && <tr><td colSpan={columns.length + 2} className="no-rows">没有数据</td></tr>}</tbody></table></div><div className="table-footer"><span>{result.total ?? result.rows.length} 行{result.truncated ? ' · 已显示前 1000 行' : ''}</span><span className="footer-spacer"/>{!readonly && <button className="add-row" onClick={onAdd}><Plus size={14}/>新增行</button>}<button className="page-btn" disabled={page === 0} onClick={() => setPage(page - 1)}>上一页</button><span>第 {page + 1} 页</span><button className="page-btn" disabled={result.rows.length < 100} onClick={() => setPage(page + 1)}>下一页</button></div></div> }

function StructureView({ structure }: { structure?: Structure }) { if (!structure) return <div className="loading-state"><Activity className="spin"/>正在读取结构…</div>; return <div className="panel structure-panel"><div className="panel-head"><div><div className="eyebrow">SCHEMA</div><h1>表结构</h1></div><span className={`badge ${structure.editable ? 'green' : 'gray'}`}>{structure.editable ? '可编辑' : '只读'}</span></div><h3>字段</h3><div className="structure-table"><table><thead><tr><th>名称</th><th>类型</th><th>非空</th><th>默认值</th><th>主键</th></tr></thead><tbody>{structure.columns.map(c => <tr key={c.name}><td className="mono">{c.name}</td><td>{c.type || '—'}</td><td>{c.notnull ? '是' : '否'}</td><td className="mono">{c.dflt_value || '—'}</td><td>{c.pk ? <span className="key-pill">PK {c.pk}</span> : '—'}</td></tr>)}</tbody></table></div><h3>建表 SQL</h3><pre className="sql-preview">{structure.sql || '没有可用的建表 SQL'}</pre>{structure.indexes.length > 0 && <><h3>索引</h3><div className="index-list">{structure.indexes.map((i: any) => <span key={i.name} className="index-pill">{i.name}</span>)}</div></>}</div> }

function QueryView({ sql, setSql, onRun, loading, result }: { sql: string; setSql: (value: string) => void; onRun: () => void; loading: boolean; result?: QueryResult }) { return <div className="query-panel"><div className="query-head"><div><div className="eyebrow">SQL EDITOR</div><h1>查询工作区</h1></div><button className="run-btn" onClick={onRun} disabled={loading}><Play size={15} fill="currentColor"/>{loading ? '执行中…' : '执行'} <kbd>⌘ Enter</kbd></button></div><div className="editor-wrap"><CodeMirror value={sql} height="220px" theme={oneDark} extensions={[sqlLanguage()]} onChange={setSql} basicSetup={{ lineNumbers: true, foldGutter: true, autocompletion: true }}/></div><div className="result-head"><div><span className="eyebrow">RESULT</span>{result && <span className="result-meta">{result.changes !== undefined ? `${result.changes} 行受影响 · ${result.elapsedMs} ms` : `${result.rows.length} 行 · ${result.elapsedMs} ms${result.truncated ? ' · 已截断' : ''}`}</span>}</div>{loading && <button className="stop-btn"><Square size={13} fill="currentColor"/>停止</button>}</div>{result && <div className="result-table"><table><thead><tr>{result.columns.map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{result.rows.map((row, i) => <tr key={i}>{result.columns.map(c => <td key={c} className={row[c] === null ? 'null-value' : ''}>{formatValue(row[c])}</td>)}</tr>)}</tbody></table>{!result.rows.length && result.changes === undefined && <div className="no-rows">查询没有返回数据</div>}</div>}</div> }

createRoot(document.getElementById('root')!).render(<App />)
